.TH "ASC" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
ASC \- <文字式>のキャラクターコードを返します。

.SH SYNOPSIS
.B ASC(<文字式>)

.SH DESCRIPTION
.PP
<文字式>のキャラクターコードを返します。

.SH EXAMPLES
.PP
PRINT ASC("a")
 [表示] 97

.SH NOTES
.PP
.PP
返される値は整数型です。
.PP
指定した<文字式>がいくつかの文字からなる文字列の場合は、
.PP
一番最初の文字のキャラクターコードが返されます。