.TH "ATN" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
ATN \- <数式>の逆正接(アークタンジェント)を返します。

.SH SYNOPSIS
.B ATN(<数式>)

.SH DESCRIPTION
.PP
<数式>の逆正接(アークタンジェント)を返します。

.SH EXAMPLES
.PP
PRINT ATN(1)*4
 [表示] 3.1415926535898

.SH NOTES
.PP
.PP
返される値は-π/2～π/2の倍精度実数で、ラジアン単位となります。
.PP
<数式> には整数型・単精度実数型・倍精度実数型の値を指定できます。