.TH "AUTO" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
AUTO \- プログラム行の先頭に行番号を自動的に発生させます。

.SH SYNOPSIS
.B AUTO[<行番号>][<,増分>]

.SH DESCRIPTION
.PP
プログラム行の先頭に行番号を自動的に発生させます。

.SH EXAMPLES
.PP
AUTO 1000,100

.SH NOTES
.PP
.PP
<行番号><増分>は省略できます。省略時は10が採用されます。
.PP
例
.PP
	AUTO
.PP
	行番号は 10 20 30 …… と付けられます。
.PP
	AUTO 100
.PP
	行番号は 100 110 120 …… と付けられます。
.PP
	AUTO ,5
.PP
	行番号は 10 15 20 …… と付けられます。
.PP
プログラム中に既に存在する行と同じ行番号が発生した場合、
.PP
行番号の後にアクタリスク(*)が表示されます。
.PP
その時、何も入力せずにリターンキーを押した場合は、
.PP
内容が残されます。
.PP
AUTO の機能を中止したい場合は [CTRL]+[C] キー
.PP
または [CTRL]+[STOP] キーを押します。