.TH "BASE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
BASE \- 画面出力に関連する VRAM 上のデーブルのアドレスを返します。

.SH SYNOPSIS
.B BASE(<数式>)

.SH DESCRIPTION
.PP
画面出力に関連する VRAM 上のデーブルのアドレスを返します。

.SH EXAMPLES
.PP
BASE(10)

.SH NOTES
.PP
.PP
<数式> で指定された VRAM 上のテーブルのアドレスを返します。
.PP
<数式> は以下のとおりです。
.PP
     0 SCREEN 0  &H0000 パターンネームテーブル
.PP
     2 SCREEN 0  &H1000 パターンジェネレータテーブル
.PP
     5 SCREEN 1  &H1800 パターンネームテーブル
.PP
     6 SCREEN 1  &H2000 カラーテーブル
.PP
     7 SCREEN 1  &H0000 パターンジェネレータテーブル
.PP
     8 SCREEN 1  &H1B00 スプライトアトリビュートテーブル
.PP
     9 SCREEN 1  &H3800 スプライトジェネレータレーブル
.PP
    10 SCREEN 2  &H1800 パターンネームテーブル
.PP
    11 SCREEN 2  &H2000 カラーテーブル
.PP
    12 SCREEN 2  &H0000 パターンジェネレータテーブル
.PP
    13 SCREEN 2  &H1B00 スプライトアトリビュートテーブル
.PP
    14 SCREEN 2  &H3800 スプライトジェネレータレーブル
.PP
    15 SCREEN 3  &H0800 パターンネームテーブル
.PP
    17 SCREEN 3  &H0000 パターンジェネレータテーブル
.PP
    18 SCREEN 3  &H1B00 スプライトアトリビュートテーブル
.PP
    19 SCREEN 3  &H3800 スプライトジェネレータレーブル
.PP
    20 SCREEN 4  &H1800 パターンネームテーブル
.PP
    21 SCREEN 4  &H2000 カラーテーブル
.PP
    22 SCREEN 4  &H0000 パターンジェネレータテーブル
.PP
    23 SCREEN 4  &H1E00 スプライトアトリビュートテーブル
.PP
    24 SCREEN 4  &H3800 スプライトジェネレータレーブル
.PP
    25 SCREEN 5  &H0000 パターンネームテーブル
.PP
    28 SCREEN 5  &H7600 スプライトアトリビュートテーブル
.PP
    29 SCREEN 5  &H7800 スプライトジェネレータレーブル
.PP
    30 SCREEN 6  &H0000 パターンネームテーブル
.PP
    33 SCREEN 6  &H7600 スプライトアトリビュートテーブル
.PP
    34 SCREEN 6  &H7800 スプライトジェネレータレーブル
.PP
    35 SCREEN 7  &H0000 パターンネームテーブル
.PP
    38 SCREEN 7  &H7600 スプライトアトリビュートテーブル
.PP
    39 SCREEN 7  &HF000 スプライトジェネレータレーブル
.PP
    40 SCREEN 8  &HFA00 パターンネームテーブル
.PP
    43 SCREEN 8  &HF000 スプライトアトリビュートテーブル
.PP
    44 SCREEN 8  &HFA00 スプライトジェネレータレーブル
.PP
    20 SCREEN 8  &HFA00 パターンネームテーブル
.PP
    53 SCREEN 8  &HF000 スプライトアトリビュートテーブル
.PP
    54 SCREEN 8  &HFA00 スプライトジェネレータレーブル
.PP
    55 SCREEN 11 &HFA00 パターンネームテーブル
.PP
    58 SCREEN 11 &HF000 スプライトアトリビュートテーブル
.PP
    59 SCREEN 11 &HFA00 スプライトジェネレータレーブル
.PP
    60 SCREEN 12 &HFA00 パターンネームテーブル
.PP
    63 SCREEN 12 &HF000 スプライトアトリビュートテーブル
.PP
    64 SCREEN 12 &HFA00 スプライトジェネレータレーブル
.PP
改めると <数式>÷5 の商(整数部) は SCREEN のスクリーンモード、
.PP
余りが次の通りとなっています。
.PP
    0 パターンネームテーブル
.PP
    1 カラーテーブル
.PP
    2 パターンジェネレータテーブル
.PP
    3 スプライトアトリビュートテーブル
.PP
    4 スプライトジェネレータレーブル