.TH "BEEP" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
BEEP \- スピーカーを鳴らします。

.SH SYNOPSIS
.B BEEP

.SH DESCRIPTION
.PP
スピーカーを鳴らします。

.SH EXAMPLES
.PP
BEEP

.SH NOTES
.PP
.PP
MSX2 以降では SET BEEP 命令で指定した
.PP
音色・大きさでスピーカーを鳴らします。
.PP
MSX(1) では音色・大きさは固定です。
.PP
（約0.04秒スピーカーを鳴らします。）
.PP
CHR$(7) を出力しても BEEP と同じ結果を得る事ができます。
.PP
例 PRINT CHR$(7)