.TH "BLOAD(1)" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
BLOAD(1) \- 機械語プログラムをメモリに読み込みます。

.SH SYNOPSIS
.B BLOAD <ファイルスペック>[,R][,<オフセット>]

.SH DESCRIPTION
.PP
機械語プログラムをメモリに読み込みます。

.SH EXAMPLES
.PP
BLOAD "MSXDEMO.BIN",R

.SH NOTES
.PP
.PP
<ファイルスペック>で指定したファイルをメモリに読み込みます。
.PP
ファイルは BSAVE で保存された形式である必要があｒます。
.PP
読み込みの開始番地は BSAVE の開始番地に
.PP
<オフセット> が加えられた番地となります。
.PP
,R が付いている場合は
.PP
読み込んだマシン語プログラムの実行を開始します。
.PP
実行開始番地は BSAVE の実行番地に
.PP
<オフセット> が加えられた番地となります。
.PP
<オフセット> の値は 0～65535 の整数です。
.PP
省略時は 0 となります。