.TH "BSAVE(1)" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
BSAVE(1) \- メモリにあるデータをファイルに保存します。

.SH SYNOPSIS
.B BSAVE <ファイルスペック>,<開始番地>,<終了番地>[,<実行番地>]

.SH DESCRIPTION
.PP
メモリにあるデータをファイルに保存します。

.SH EXAMPLES
.PP
BSAVE "MSXDEMO.BIN",&HA000,&HAFFF

.SH NOTES
.PP
.PP
<開始番地> から <終了番地> までの
.PP
メモリ上のデータをファイルに保存します。
.PP
マシン語プログラムである場合は <実行番地> を記載する事で
.PP
BLOAD,R によってその番地から実行が行なえます。
.PP
<開始番地> <終了番地> <実行番地> の値は
.PP
&H8000～&HFFFF の整数です。
.PP
<実行番地> を省略した場合は <開始番地> と同じ値になります。