.TH "CALL TEMPER" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL TEMPER \- MSX-MUSIC での音律を設定します。

.SH SYNOPSIS
.B CALL MUSIC(<音律>)

.SH DESCRIPTION
.PP
MSX-MUSIC での音律を設定します。

.SH EXAMPLES
.PP
CALL MUSIC(0)

.SH NOTES
.PP
.PP
<音律> は以下の通りです。初期値は 9 となっています。
.PP
    0  ピタコラス
.PP
    1  ミーントーン
.PP
    2  ヴェルクマイスター
.PP
    3  ヴェルクマイスター(修正)
.PP
    4  ヴェルクマイスター(別)
.PP
    5  キルンベルガー
.PP
    6  キルンベルガー(修正)
.PP
    7  ヴァロッティ・ヤング
.PP
    8  ラモー
.PP
    9  完全平均律
.PP
    10 純正律 c メジャー (a マイナー)
.PP
    11 純正律 cis メジャー (b マイナー)
.PP
    12 純正律 d メジャー (h マイナー)
.PP
    13 純正律 es メジャー (c マイナー)
.PP
    14 純正律 e メジャー (cis マイナー)
.PP
    15 純正律 f メジャー (d マイナー)
.PP
    16 純正律 fis メジャー (es マイナー)
.PP
    17 純正律 g メジャー (e マイナー)
.PP
    18 純正律 gis メジャー (f マイナー)
.PP
    19 純正律 a メジャー (fis マイナー)
.PP
    20 純正律 b メジャー (g マイナー)
.PP
    21 純正律 h メジャー (gis マイナー)