.TH "CALL JIS" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL JIS \- 全角１文字のJISコードを得ます。

.SH SYNOPSIS
.B CALL JIS(<文字変数>,<文字列>)

.SH DESCRIPTION
.PP
全角１文字のJISコードを得ます。

.SH EXAMPLES
.PP
CALL JIS(KA$,"漢字書けな～い！"):PRINT KA$
 [表示] 3441

.SH NOTES
.PP
.PP
<文字列> の最初の全角1文字(2バイト)が有効です。
.PP
結果は <文字変数> に入ります。