.TH "CALL MNAME" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL MNAME \- メモリディスク上のファイル名を変更します。

.SH SYNOPSIS
.B CALL MNAME(<旧ファイル名> AS <新ファイル名>)

.SH DESCRIPTION
.PP
メモリディスク上のファイル名を変更します。

.SH EXAMPLES
.PP
CALL MNAME("NFILE.BAS" AS "FILE.BAS")

.SH NOTES
.PP
.PP
<旧ファイル名> <新ファイル名> に
.PP
ワイルドカードを使用する事はできません。