.TH "CALL PALETTE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL PALETTE \- カラーパレットの設定・初期化を行ないます。

.SH SYNOPSIS
.B CALL PALETTE[(<パレット>,<赤>,<緑>,<青>)]

.SH DESCRIPTION
.PP
カラーパレットの設定・初期化を行ないます。

.SH EXAMPLES
.PP
CALL PALETTE(14,3,3,3)

.SH NOTES
.PP
.PP
漢字テキストモードでパレットを変更する際に利用します。
.PP
（COLOR= の代わり）
.PP
漢字 BASIC 搭載の MSX であれば、
.PP
漢字モードでない場合でも利用可能です。