.TH "CALL TRANSPOSE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL TRANSPOSE \- MSX-MUSIC で移調を設定します。

.SH SYNOPSIS
.B CALL TRANSPOSE(<値1>)

.SH DESCRIPTION
.PP
MSX-MUSIC で移調を設定します。

.SH EXAMPLES
.PP
CALL TRANSPOSE(0)

.SH NOTES
.PP
.PP
<値1> は -12799～12799 で、セント(半音の1/100)単位です。
.PP
初期値は 0 となっています。
.PP
なお、MSX-AUDIO には <値2> も存在しますが、
.PP
MSX-MUSIC では用いないため、ここでは記載を省略しています。