.TH "CALL PCMREC" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL PCMREC \- PCM を録音します。

.SH SYNOPSIS
.B CALL PCMREC( { @<開始番地>,<終了番地> | <配列変数名>,[長さ] }
,<レート>,<開始レベル>,<圧縮>[,S])

.SH DESCRIPTION
.PP
PCM を録音します。

.SH EXAMPLES
.PP
CALL PCMREC(@&HB000,&HBFFF,1)

.SH NOTES
.PP
.PP
<開始番地> <終了番地> の指定を &H10000 以上にする場合は
.PP
10 進数表記にする必要があります。
.PP
これは MSX-BASIC の16進数が
.PP
最大で &HFFFF（65535）である事からです。
.PP
また &H8000～&HFFFF は負の値となるため、
.PP
計算で 16 進数を用いる場合もご注意ください。
.PP
<長さ> を省略した場合は配列変数の内容を全て再生します。
.PP
<レート> は以下の通りです。
.PP
    0 15.75KHz
.PP
    1  7.875KHz
.PP
    2  5.25KHz
.PP
    3  3.9375KHz
.PP
<開始レベル> は録音を開始する時のレベルで、0～127 です。
.PP
省略時は 0 となります。0 にするとただちに録音が開始されます。
.PP
<圧縮> はデータが無音の際に圧縮を行なうかどうかを指定します。
.PP
省略時は 0 となります。
.PP
	0	圧縮しない
.PP
	1	圧縮する
.PP
,S をつけた場合は VRAM からの再生となります。
.PP
つけない場合は RAM からの再生となります。
.PP
PCM データはアブソリュートバイナリで、
.PP
1～255 がデータとなります。
.PP
<圧縮> を 1 にした場合は 0 レベル付近(126～128) を
.PP
0 の場合は続く 1 バイトの回数分を出力して
.PP
無音データを圧縮します。
.PP
実行は CPU が Z80 である場合、R800 に切り替えられて録音されます。
.PP
録音が終了すると Z80 に戻されます。
.PP
<レート> が 0（15.75KHz）の場合は
.PP
Z800 DRAM モードで実行される必要があります。
.PP
録音中に [STOP] を押した場合は BASIC の実行を中断します。