.TH "CALL CLS" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL CLS \- 漢字モードで画面をクリアします。

.SH SYNOPSIS
.B CALL CLS

.SH DESCRIPTION
.PP
漢字モードで画面をクリアします。

.SH EXAMPLES
.PP
CALL CLS

.SH NOTES
.PP
.PP
漢字モードでは CLS が使えないため、
.PP
代わりに CALL CLS を用います。
.PP
漢字 BASIC が使える MSX であれば、
.PP
漢字モード以外でも CALL CLS は使用可能です。