.TH "CALL RMDIR" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CALL RMDIR \- ディレクトリを削除します。

.SH SYNOPSIS
.B CALL RMDIR(<ドライブ>:<パス>)

.SH DESCRIPTION
.PP
ディレクトリを削除します。

.SH EXAMPLES
.PP
CALL RMDIR("H:\TEMP")

.SH NOTES
.PP
.PP
ディレクトリは Windows・macOS でいうフォルダの事です。
.PP
ワイルドカードにより複数のディレクトリを削除する事も出来ます。