.TH "CIRCLE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CIRCLE \- 円・楕円を描きます。

.SH SYNOPSIS
.B CIRCLE [STEP] (<横座標>,<縦座標>),<半径>[,<カラーコード>]
[,<開始角度>][,<終了角度>][,<比率>]

.SH DESCRIPTION
.PP
円・楕円を描きます。

.SH EXAMPLES
.PP
CIRCLE (128,128),80,10,3.14/2,3.14*2,2

.SH NOTES
.PP
.PP
STEP を付けると最終座標からの相対座標となります。
.PP
<カラーコード> を省略した場合は
.PP
COLOR の前景色を用いて円を描きます。
.PP
<開始角度> <終了角度> はラジアン単位です。（π＝180 度）
.PP
省略した場合は 0＝2π となります。
.PP
　　　　2π/4
.nf
 3π/4 ＊＊＊  π/4
　　 ＊　｜　＊
　 ＊　　｜　　＊
π ＊－－＋－－＊ 0・2π
　 ＊　　｜　　＊
　　 ＊　｜　＊
 5π/4 ＊＊＊　7π/4
.fi
.PP
　　　　6π/4
.PP
<比率> は (横の半径)/(縦の半径) です。省略時は 1 となります。