.TH "CLOAD？" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CLOAD？ \- カセットテープ上のプログラムと
メモリ上にあるプログラムで比較します。

.SH SYNOPSIS
.B CLOAD? [<ファイル名>]

.SH DESCRIPTION
.PP
カセットテープ上のプログラムと
メモリ上にあるプログラムで比較します。

.SH EXAMPLES
.PP
CLOAD? "LOAD"

.SH NOTES
.PP
.PP
カセットテープから <ファイル名> のプログラムを探し、
.PP
メモリ上のプログラムと比較します。
.PP
省略された場合は最初に見つけたプログラムが読み込まれます。