.TH "CLOSE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CLOSE \- ファイルを閉じます。

.SH SYNOPSIS
.B CLOSE [[#]<ファイル番号> [,[#]<ファイル番号> ...]]

.SH DESCRIPTION
.PP
ファイルを閉じます。

.SH EXAMPLES
.PP
CLOSE #1

.SH NOTES
.PP
.PP
OPEN で開いたファイルを閉じます。
.PP
ファイルは複数指定して同時に閉じる事ができます。
.PP
また CLOSE のみにすると
.PP
開いているファイルを全て閉じる事ができます。
.PP
実際の動作では、
.PP
CLOSE によってバッファに残っているデータを
.PP
ファイルに書き出す処理を行なっています。
.PP
従って、開いているファイルは閉じる事で
.PP
出力処理を完了するようにします。
.PP
なお、END や NEW によってもクローズ処理は行なわれますが、
.PP
STOP ではクローズ処理は行なわれません。