.TH "CLS" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CLS \- 画面をクリアします。

.SH SYNOPSIS
.B CLS

.SH DESCRIPTION
.PP
画面をクリアします。

.SH EXAMPLES
.PP
CLS

.SH NOTES
.PP
.PP
画面に表示されている文字や図形・絵を消去します。
.PP
スプライト・テキスト表示で KEY ON にしている場合に
.PP
ファンクションキーの表示はクリアの対象ではありません。
.PP
テキスト表示では、カーソルは左上（座標 0,0）へ移動します。
.PP
グラフィックでは最終座標を維持します。
.PP
漢字モードのクリアは CLS の代わりに CALL CLS を用います。