.TH "COLOR=RESTORE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
COLOR=RESTORE \- カラーコードの色を
VRAM のパレットテーブルに従って変更します。

.SH SYNOPSIS
.B COLOR=RESTORE

.SH DESCRIPTION
.PP
カラーコードの色を
VRAM のパレットテーブルに従って変更します。

.SH EXAMPLES
.PP
COLOR=RESTORE

.SH NOTES
.PP
.PP
例えば BSAVE でパレットテーブル部分を保存したファイルを
.PP
BLOAD で読み込んだ後、COLOR=RESTORE を実行する事で、
.PP
保存した状態の色で表示が行なわれます。