.TH "COLOR SPRITE$" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
COLOR SPRITE$ \- スプライト面の色を 1 行毎で指定します。

.SH SYNOPSIS
.B COLOR SPRITE$(<スプライト面番号>)=<カラーコード列>

.SH DESCRIPTION
.PP
スプライト面の色を 1 行毎で指定します。

.SH EXAMPLES
.PP
COLOR SPRITE(0)=STRING$(16,&HFF)

.SH NOTES
.PP
.PP
<カラーコード列> 以下の値を1行毎に指定します。
.PP
    bit7    32 ドット左にずらして表示
.PP
            1=行なう 0=行なわない
.PP
    bit6    重ね表示
.PP
            1=行なう 0=行なわない
.PP
    bit5    衝突検出
.PP
            1=検出しない 0=検出する
.PP
    bit4    未使用
.PP
    bit3～0 カラーコード
.PP
「32 ドット左にずらして表示」は
.PP
通常 X 座標が 0～255 で処理されますが、
.PP
この bit を ON にする事で -32～223 とします。
.PP
左端からスプライトを少しだけ表示されるのに役立ちます。
.PP
「重ね表示」は例えばスプライト 0 を 0、
.PP
スプライト 1 を 1 とした場合に
.PP
スプライト 0 とスプライト 1 を重ねて表示させます。
.PP
この際、二つのスプライトが重なっている部分は
.PP
色コードが OR となります。
.PP
この 2 つのスプライトは衝突検出の対象にはなりません。
.PP
PUT SPRITE はスプライト 0 で座標を指定する事で
.PP
スプライト 1 も一緒に動作します。
.PP
また、スプライト 0 が非表示である場合は
.PP
スプライト 1 も非表示となります。
.PP
ここでは二つのスプライトで説明していますが、
.PP
三つ以上でも動作します。
.PP
「衝突検出」が bit ON になっている場合、
.PP
その行が重なっても衝突検出の対象になりません。
.PP
「カラーコード」は SCREEN 8 の場合、
.PP
以下の固定色となります。
.PP
                赤(R) 緑(G) 青(B)
.PP
     0 黒       0     0     0
.PP
     1 暗い青   0     0     2
.PP
     2 暗い赤   3     0     0
.PP
     3 暗い紫   3     0     2
.PP
     4 暗い緑   0     3     0
.PP
     5 暗い水色 0     3     2
.PP
     6 暗い黄色 3     3     0
.PP
     7 灰色     3     3     2
.PP
     8 肌色     7     4     2
.PP
     9 青       0     0     7
.PP
    10 赤       7     0     0
.PP
    11 紫       7     0     7
.PP
    12 緑       0     7     0
.PP
    13 水色     0     7     7
.PP
    14 黄色     7     7     0
.PP
    15 白       7     7     7
.PP
また、SCREEN 6 では奇数番目と偶数番目で
.PP
異なる色を設定できます。
.PP
bit 3・2 が奇数番目の色コード、
.PP
bit 1・0 が偶数番目の色コードです。
.PP
これにより擬似的に 10 色指定できるようになっています。