.TH "CONT" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
CONT \- プログラムの実行を再開します。

.SH SYNOPSIS
.B CONT

.SH DESCRIPTION
.PP
プログラムの実行を再開します。

.SH EXAMPLES
.PP
CONT

.SH NOTES
.PP
.PP
プログラムを [CTRL]+{STOP] による実行中断や
.PP
STOP・END 文による実行停止を行なった場合に
.PP
CONT を用いて実行を再開する事ができます。
.PP
プログラムの変更を行なった場合、再開は行なえません。