.TH "COPY(2)" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
COPY(2) \- 配列変数・VRAM・ディスク間でデータの転送を行ないます。

.SH SYNOPSIS
.B COPY {  (<転送元左上座標>)-(<転送元右下座標>)[,<転送元ページ番号>]
      | <配列変数名>[,<転送方向>] 
      | <ファイルスペック>[,<転送方向>]  }
     TO 
     {  (<転送先座標>)[,<転送先ページ番号>][,<論理演算子>]
      | <配列変数名>
      | <ファイルスペック>  }

.SH DESCRIPTION
.PP
配列変数・VRAM・ディスク間でデータの転送を行ないます。

.SH EXAMPLES
.PP
COPY (0,0)-(255,211),1 TO (0,0),0
COPY (0,0)-(15,15),0 TO "MSX.CP5"
COPY CP% TO (0,0),0

.SH NOTES
.PP
.PP
VRAM を伴なう指定は SCREEN 5 以降で有効となります。
.PP
また <ファイルスペック> は DiskBASIC が使える環境で有効となります。
.PP
<転送元左上座標> <転送元右下座標> <転送先座標> は
.PP
画面外での指定も可能です。
.PP
<転送元ページ番号> が省略された場合は
.PP
SET PAGE で指定されている <線画ページ> となります。
.PP
<転送先ページ番号> が省略された場合は
.PP
<転送元ページ番号> と同じページとなります。
.PP
<論理演算子> は省略時は PSET となります。
.PP
S が線画を行なうデータの色・D は線画される背景色です。
.PP
    PSET   S
.PP
    PRESET not S
.PP
    AND    S and D
.PP
    OR     S or D
.PP
    XOR    S xor D
.PP
    [参考] 論理演算子の仕組み
.PP
           bit 毎に以下の計算が行われます。
.PP
    S       0 0 1 1
.PP
    D       0 1 0 1
.PP
    not S   1 1 0 0 否定
.PP
    S and D 0 0 0 1 論理積
.PP
    S or D  0 1 1 1 論理和
.PP
    S xor D 0 1 1 0 排他的論理和
.PP
この５つの他、TPSET TPRESET TAND TOR TXOR があります。
.PP
T がついている場合は S が透明色である 0 である場合は
.PP
線画を行なわずに背景色 D を表示します。
.PP
<転送方向> は VRAM へ書き込む時の方向を指定します。
.PP
その先の<転送先座標>は線画を始める座標となります。
.PP
    0 左上から右下へ（通常）
.PP
    1 右上から左下へ（左右反転）
.PP
    2 左下から右上へ（上下反転）
.PP
    3 右下から左上へ（上下・左右反転）