.TH "DIM" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
DIM \- 配列変数を定義します。

.SH SYNOPSIS
.B DIM <変数名>(<最大値>[,<最大値> ...])
[,<変数名>(<最大値>[,<最大値> ...]) ...]

.SH DESCRIPTION
.PP
配列変数を定義します。

.SH EXAMPLES
.PP
DIM Q(9,9),A(9)

.SH NOTES
.PP
.PP
定義される値は 0 からとなります。
.PP
例えば N(10) の場合は N(0)～N(10) で
.PP
11 個の配列が定義される事になります。
.PP
<最大値> の数は最大で 255 次元です。
.PP
配列変数は初期状態でも使用できますが、
.PP
その場合の最大値は 10 です。
.PP
また配列の次元数は 3 となっています。
.PP
定義された配列変数は文字式の場合はヌル・ストリングに、
.PP
数値式の場合は 0 に初期化されます。
.PP
カッコは ( ) 以外に [ ]  も指定が可能です。
.PP
定義の解除は ERASE または CLEAR で行なわれます。