.TH "DRAW" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
DRAW \- 図形を線画します。

.SH SYNOPSIS
.B DRAW <文字式>

.SH DESCRIPTION
.PP
図形を線画します。

.SH EXAMPLES
.PP
DRAW "BM100,100BR50R50F50D50G50L50H50U50L50"

.SH NOTES
.PP
.PP
クラフィックモード（SCREEN 2～8・10～12）で有効です。
.PP
<文字式>は以下の通りです。
.PP
    Ｈ　Ｕ　Ｅ
.nf
    　＼｜／
    Ｌ－・－Ｒ
    　／｜＼
.fi
.PP
    Ｇ　Ｄ　Ｆ
.PP
    U<距離>        上へ移動。<距離>の省略時は 1。
.PP
    D<距離>        下へ移動。<距離>の省略時は 1。
.PP
    L<距離>        左へ移動。<距離>の省略時は 1。
.PP
    R<距離>        右へ移動。<距離>の省略時は 1。
.PP
    E<距離>        右上へ移動。<距離>の省略時は 1。
.PP
    F<距離>        右下へ移動。<距離>の省略時は 1。
.PP
    G<距離>        左下へ移動。<距離>の省略時は 1。
.PP
    H<距離>        左上へ移動。<距離>の省略時は 1。
.PP
    M[<横>][,<縦>] 座標へ移動する。
.PP
                   +・- を付加する事で相対移動も可能。
.PP
    B              座標移動を行なうが、線画しない
.PP
    N              線画するが、座標移動を行なわない
.PP
    A<角度>        その後の線画を回転した形で線画する。
.PP
                   値は 0～3 で、0・90・180・270度回転。初期値は 0。
.PP
    C<色>          線画色を指定。
.PP
    S<倍率>        値は 1～4。値の 1/4 で線画される。初期値は 4。
.PP
    X<文字型変数>; 文字型変数に記載した命令に置き換える
.PP
    =<数値型変数>; 数値型変数に記載した数値に置き換える
.PP
PSET・PRESET は線画が行われますが、
.PP
DRAW"BMx,y" では線画を行わないため
.PP
線画をしない位置移動に有効です。