.TH "FILES" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
FILES \- ディスク上のファイル・ディレクトリ一覧を表示します。

.SH SYNOPSIS
.B FILES<ファイル名><,L>

.SH DESCRIPTION
.PP
ディスク上のファイル・ディレクトリ一覧を表示します。

.SH EXAMPLES
.PP
FILES "*.*",L

.SH NOTES
.PP
.PP
<ファイル名> にはドライブ、
.PP
Disk BASIC 2 以降ではパスを含むことができます。
.PP
またワイルドカードで指定も可能です。
.PP
<,L> は Disk BASIC 2 以降で有効です。
.PP
ロングフォーマット形式により表示を行ないます。