.TH "FRE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
FRE \- 未使用容量を得ます。

.SH SYNOPSIS
.B FRE(<{数式|文字式}>)

.SH DESCRIPTION
.PP
未使用容量を得ます。

.SH EXAMPLES
.PP
FRE(0)

.SH NOTES
.PP
.PP
<数式> の場合は BASIC で利用できる空容量をバイト単位で得ます。
.PP
<文字式> の場合は文字領域が最適化された後、
.PP
文字領域の空容量をバイト単位で得ます。
.PP
<数式> <文字式> の値は関係なく、型だけが対象となります。