.TH "INPUT" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
INPUT \- キーボード・ファイルから入力されたデータを変数に入れます。

.SH SYNOPSIS
.B INPUT { [<プロンプト>;] | #<ファイル番号> }<変数名>[,<変数名> ...]

.SH DESCRIPTION
.PP
キーボード・ファイルから入力されたデータを変数に入れます。

.SH EXAMPLES
.PP
INPUT "anata no onamae nanntehno";N$

.SH NOTES
.PP
.PP
<ファイル番号> を入れない場合は
.PP
キーボードからの入力を受け付けます。
.PP
<プロンプト> があればそれを表示し、
.PP
? を後につけてカーソルを表示し、入力を促します。
.PP
入力された内容が <変数名> に入ります。
.PP
複数の <変数名> がある場合は
.PP
, で区切って入力する事で一括して変数に入れる事ができます。
.PP
一つだけ入力された場合は ?? と表示され、
.PP
次の変数への入力を促します。
.PP
グラフィック画面（SCREEN 2～8・10～12）の場合は
.PP
テキスト画面に戻ります。
.PP
なお、入力で空白や , を含む場合は " で囲む事で受け付けされます。
.PP
<ファイル番号> が入っている場合は、
.PP
そのファイルから入力を受け付けます。
.PP
<ファイル番号> のファイルは OPEN により
.PP
INPUT モードで開かれている必要があります。
.PP
ファイル中では、空白・改行・ , 以外の文字が
.PP
データの区切りと成ります。
.PP
また、" で囲まれたものは
.PP
それで一つのデータと見なされます。
.PP
255 文字までを一度に読み込みます。