.TH "INPUT$" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
INPUT$ \- ファイル・キーボードから指定長の文字列を入力します。

.SH SYNOPSIS
.B INPUT$(<入力文字数>[,[#]<ファイル番号>])

.SH DESCRIPTION
.PP
ファイル・キーボードから指定長の文字列を入力します。

.SH EXAMPLES
.PP
I$=INPUT$(1,#1)

.SH NOTES
.PP
.PP
<入力文字数> の入力を行い、その結果を返します。
.PP
<ファイル番号> の記載がある場合はそのファイルから入力を行い、
.PP
記載がない場合はキーボードからの入力となります。
.PP
入力がない場合は行なわれるまで待ち状態となります。
.PP
INPUT$ では画面の出力は行ないません。
.PP
INPUT$ は得られる文字列の長さが固定長となります。
.PP
入力文字は [CTRL]+[STOP] 以外を得る事ができます。
.PP
INPUT・LINE INPUT では受け取れない
.PP
[RETURN] もコントロールコードで受け取る事が可能です。
.PP
INKEY$ と INPUT$(1) の違いは未入力の時にヌルが返されるか、
.PP
入力待ち状態状態になるかが異なります。