.TH "INTERVAL STOP" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
INTERVAL STOP \- ON INTERVAL GOSUB による割り込みを一時停止します。

.SH SYNOPSIS
.B INTERVAL STOP

.SH DESCRIPTION
.PP
ON INTERVAL GOSUB による割り込みを一時停止します。

.SH EXAMPLES
.PP
INTERVAL STOP

.SH NOTES
.PP
.PP
INTERVAL STOP は INTERVAL ON が実行されている場合に有効です。