.TH "LEFT$" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
LEFT$ \- 文字列の左側から指定された数の文字列を取り出します。

.SH SYNOPSIS
.B LEFT$(<文字列>,<数式>)

.SH DESCRIPTION
.PP
文字列の左側から指定された数の文字列を取り出します。

.SH EXAMPLES
.PP
PRINT LEFT$("MSX ver 1.0?",3)
 [表示] MSX

.SH NOTES
.PP
.PP
指定した数が文字列の総数より大きい場合は
.PP
文字列がそのまま取り出されます。