.TH "LFILES" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
LFILES \- ディスク上のファイル・ディレクトリ一覧をプリンターに印刷します。

.SH SYNOPSIS
.B LFILES<ファイル名><,L>

.SH DESCRIPTION
.PP
ディスク上のファイル・ディレクトリ一覧をプリンターに印刷します。

.SH EXAMPLES
.PP
LFILES "*.*",L

.SH NOTES
.PP
.PP
<ファイル名> にはドライブ、
.PP
Disk BASIC 2 以降ではパスを含むことができます。
.PP
またワイルドカードで指定も可能です。
.PP
<,L> は Disk BASIC 2 以降で有効です。
.PP
ロングフォーマット形式により印刷を行ないます。