.TH "LINE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
LINE \- 線・長方形を描きます。

.SH SYNOPSIS
.B LINE[[STEP](<開始横座標>,<開始縦座標>)]-
[STEP](<終了横座標>,<終了横座標>)
[,<色>][,B[F]][,<論理演算子>]

.SH DESCRIPTION
.PP
線・長方形を描きます。

.SH EXAMPLES
.PP
LINE (100,100)-(150,150),10,B

.SH NOTES
.PP
.PP
<開始横座標>,<開始縦座標> から
.PP
<終了横座標>,<終了横座標> へ線を引きます。
.PP
STEP を(<開始横座標>,<開始縦座標>) の前につけた場合は
.PP
PSET・DRAW 等で指定された最終座標からの相対位置となります。
.PP
また STEP を(<終了横座標>,<終了縦座標>) の前につけた場合は、
.PP
<開始横座標>,<開始縦座標> からの相対位置となります。
.PP
(<開始横座標>,<開始縦座標>) を省略した場合は
.PP
PSET・DRAW 等で指定された最終座標となります。
.PP
<色> を省略した場合は COLOR で指定された
.PP
<前景色> が対象となります。
.PP
,B を指定した場合は <開始横座標>,<開始縦座標> と
.PP
<終了横座標>,<終了横座標> の2点を対角をした正方形を描きます。
.PP
,BF とした場合はその正方形の中を塗りつぶします。
.PP
<論理演算子> は省略時は PSET となります。
.PP
S が線画を行なうデータの色・D は線画される背景色です。
.PP
    PSET   S
.PP
    PRESET not S
.PP
    AND    S and D
.PP
    OR     S or D
.PP
    XOR    S xor D
.PP
    [参考] 論理演算子の仕組み
.PP
           bit 毎に以下の計算が行われます。
.PP
    S       0 0 1 1
.PP
    D       0 1 0 1
.PP
    not S   1 1 0 0 否定
.PP
    S and D 0 0 0 1 論理積
.PP
    S or D  0 1 1 1 論理和
.PP
    S xor D 0 1 1 0 排他的論理和
.PP
この 5 種類、TPSET TPRESET TAND TOR TXOR があります。
.PP
T がついている場合は S が透明色である 0 である場合は
.PP
線画を行なわずに背景色 D を表示します。