.TH "LOC" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
LOC \- ファイルの参照位置を得ます。

.SH SYNOPSIS
.B LOC(<ファイル番号>)

.SH DESCRIPTION
.PP
ファイルの参照位置を得ます。

.SH EXAMPLES
.PP
SI=LOC(1)

.SH NOTES
.PP
.PP
ランダムファイルである場合、
.PP
返される値は入出力によるレコード番号を得ます。
.PP
ファイルを開いた直後は 0 です。
.PP
シーケンシャルファイルである場合は
.PP
読み書きされたサイズを得ます。
.PP
単位はバイトですが、
.PP
MSX BASIC では 256 バイト毎で読み書きを行なう為に、
.PP
得られる値も 256 バイト単位となります。
.PP
ファイルを開いた直後は 256 バイト以上の場合は 256 バイト、
.PP
256 バイト未満の場合はファイルサイズとなります。