.TH "LPRINT USING" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
LPRINT USING \- 数字や文字列を書式化して印刷します。

.SH SYNOPSIS
.B PRINT USING <書式>;<式> ...

.SH DESCRIPTION
.PP
数字や文字列を書式化して印刷します。

.SH EXAMPLES
.PP
LPRINT USING"& & &   $ ### !";"MSX";"BASIC",2.5,"???"

.SH NOTES
.PP
.PP
<書式> は以下の通りです。
.PP
<式> の数が <書式> より多い場合は
.PP
再度先頭の <書式> から採用されます。
.PP
    !    文字列の先頭1文字
.PP
    & &  && を含む文字数の文字列。
.PP
         長い場合は切り捨て・短い場合は空白
.PP
    @    文字列全文字
.PP
    #    数値。# の文字数が桁数となる。
.PP
         少ない場合は右詰め。多い場合は % を頭に付けて表示
.PP
    .    小数点。小数点より右に # があり、
.PP
         満たない場合は 0 が付加される
.PP
    +    正負表示。正は +、負は - を表示
.PP
    -    正負表示。正は空白、負は - を表示
.PP
    **   ## の代わりに利用でき、桁数が少ない場合は * が表示される
.PP
    \\   \ を表示。１文字分は # 扱いとなる
.PP
    **\  \ を表示し、桁数が少ない場合は * が表示される。
.PP
    ,    整数部の右端（ . の前）に付ける事で3桁毎に , で区切る
.PP
    ^^^^ 指数表示
.PP
<式> は複数指定でき、その際の区切りは ; または , を使用できます。