.TH "LPRINT" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
LPRINT \- 数字や文字列を印刷します。

.SH SYNOPSIS
.B LPRINT [<式> ...]

.SH DESCRIPTION
.PP
数字や文字列を印刷します。

.SH EXAMPLES
.PP
LPRINT A$,B,"MSX";"?"

.SH NOTES
.PP
.PP
複数の<式>を連結する文字として ; と , が使用できます。
.PP
; は間がありません。, は 14 桁区切りで表示されます。
.PP
PRINT の最後に ; がある場合は改行が行なわれません。
.PP
ない場合は改行を行ないます。
.PP
また PRINT のみの場合は改行が行なわれます。
.PP
<式> が数値の場合、左 1 文字分が符号表示となります。
.PP
正の場合はスペース、負の場合は - となります。
.PP
また、後にも 1 文字分の空白が付加されます。
.PP
数値が単精度実数型・倍精度実数型の場合、
.PP
それぞれ 6 桁・14 桁までは実数で表記されますが、
.PP
それ以上の桁数を持つ場合は指数表記となります。
.PP
PRINT の代わりに ? を用いる事もできます。