.TH "MKD$" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
MKD$ \- 倍精度実数型を文字型に変換します。

.SH SYNOPSIS
.B MKD$(<数式>)

.SH DESCRIPTION
.PP
倍精度実数型を文字型に変換します。

.SH EXAMPLES
.PP
LSET FI$=MKD$(DD#)

.SH NOTES
.PP
.PP
ランダムアクセスファイルは文字型しか扱えないため、
.PP
変数の型を変換するために用意されています。
.PP
MKD$ により倍精度実数型は8バイトの文字型に変化させる機能です。
.PP
これを戻す場合は CVD を用います。