.TH "MKS$" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
MKS$ \- 単精度実数型を文字型に変換します。

.SH SYNOPSIS
.B MKS$(<数式>)

.SH DESCRIPTION
.PP
単精度実数型を文字型に変換します。

.SH EXAMPLES
.PP
LSET FI$=MKS$(SS!)

.SH NOTES
.PP
.PP
ランダムアクセスファイルは文字型しか扱えないため、
.PP
変数の型を変換するために用意されています。
.PP
MKI$ により単精度実数型は4バイトの文字型に変化させる機能です。
.PP
これを戻す場合は CVS を用います。