.TH "ON GOTO" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
ON GOTO \- 値に応じて指定行へ制御を移します。

.SH SYNOPSIS
.B ON <数式> GOTO <行番号>[,<行番号>]

.SH DESCRIPTION
.PP
値に応じて指定行へ制御を移します。

.SH EXAMPLES
.PP
ON SW GOTO 110,120,130

.SH NOTES
.PP
.PP
<数式> に応じて指定された <行番号> へ制御を移します。
.PP
<数式> が 0 または <行番号> の数より多い場合は、
.PP
ON GOTO の次の文へ移ります。