.TH "PAD" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
PAD \- マウス等の状態を得ます。

.SH SYNOPSIS
.B PAD(<値>)

.SH DESCRIPTION
.PP
マウス等の状態を得ます。

.SH EXAMPLES
.PP
S=PAD(12):X=PAD(13):Y=PAD(14)

.SH NOTES
.PP
.PP
<値> は以下の通りです。
.PP
8 以降は MSX 2 以降で有効ですが、
.PP
8～11 は MSX turbo R で無効となっています。（ 0 が返ります）
.PP
MSXPLAYer でもマウス以外は有効ではないかもしれません。
.PP
     0 ポート1のタブレット状態
.PP
       -1=有効 0=無効
.PP
     1 ポート1のタブレットX座標
.PP
     2 ポート1のタブレットY座標
.PP
     3 ポート1のタブレットスイッチ状態
.PP
       -1=押されている 0=押されていない
.PP
     4 ポート2のタブレット状態
.PP
       -1=有効 0=無効
.PP
     5 ポート2のタブレットX座標
.PP
     6 ポート2のタブレットY座標
.PP
     7 ポート2のタブレットスイッチ状態
.PP
       -1=押されている 0=押されていない
.PP
     8 ライトペンの状態
.PP
       -1=有効 0=無効
.PP
     9 ライトペンX座標
.PP
    10 ライトペンY座標
.PP
    11 ライトペンスイッチ状態
.PP
       -1=押されている 0=押されていない
.PP
    12 ポート1のマウス・トラックボール状態
.PP
       常に-1
.PP
    13 ポート1のマウス・トラックボールX座標
.PP
    14 ポート1のマウス・トラックボールY座標
.PP
    15 ポート1のマウス・トラックボール状態
.PP
       常に0
.PP
    16 ポート2のマウス・トラックボール状態
.PP
       常に-1
.PP
    17 ポート2のマウス・トラックボールX座標
.PP
    18 ポート2のマウス・トラックボールY座標
.PP
    19 ポート2のマウス・トラックボール状態
.PP
       常に0
.PP
それぞれ 0・4・8・12・16 を実行して
.PP
有効性を調べた後に他のデータを得ます。
.PP
0・4・8・12・16 実行時で他の値も入るようになっています。
.PP
そのため、間隔はあけずに他のデータを取得する必要があります。