.TH "PLAY(2)" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
PLAY(2) \- 音楽を演奏中を調べる

.SH SYNOPSIS
.B PLAY(<チャンネル番号>)

.SH DESCRIPTION
.PP
音楽を演奏中を調べる

.SH EXAMPLES
.PP
P=PLAY(0)

.SH NOTES
.PP
.PP
<チャンネル番号> は 0～3 です。
.PP
0 の場合はチャンネル番号 1～3 いずれかが
.PP
演奏されている場合は -1、
.PP
いずれも演奏されていない場合は 0 を返します。
.PP
1～3 の場合はそれぞれのチャンネル番号の演奏状態を返し、
.PP
演奏されている場合は -1、
.PP
演奏されていない場合は 0 を返します。