.TH "PLAY(1)" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
PLAY(1) \- 音楽を演奏する

.SH SYNOPSIS
.B PLAY <MML1>[,<MML2>][,<MML3>]

.SH DESCRIPTION
.PP
音楽を演奏する

.SH EXAMPLES
.PP
PLAY "O4L4CDEFEDCREFGAGFERCRCRCRCRL8CCDDEEFFL4EDCR"

.SH NOTES
.PP
.PP
<MML1> <MML2> <MML3> に記載する MML は以下の通りです。
.PP
    T<テンポ>      1分間に演奏する4分音符の数。
.PP
                   値は32～255。初期値は 120。
.PP
    O<オクターブ>  値は1～8。初期値は 4。
.PP
    L<音長>        <音長> 省略時の音長
.PP
                   1～64 で 1 が全音符～64 が 64 分音符
.PP
                   初期値は 4。
.PP
    A～G<音長>     CDEFGAB でハ長調の ドレミファソラシ。
.PP
                   <音長> 省略時は L の値
.PP
    #・+           シャープ。半音上げます
.PP
    -              フラット。半音下げます
.PP
    R<音長>        休符
.PP
                   <音長> 省略時は L の値
.PP
    N<音域>        値は0～96。
.PP
                   N0＝休符
.PP
                   N1＝O1C+
.PP
                   　：
.PP
                   N96＝O8B
.PP
    V<音量>        0～15 で 0 が最小、15 が最大。
.PP
    S<形状>        エンベローブ形状。以下の通り。
.PP
                   ￣= V15　＿ = V0　／ = V0→V15　＼ V0→V15
.PP
                    0 ＼＿＿＿＿＿＿＿
.PP
                    1 ＼＿＿＿＿＿＿＿
.PP
                    2 ＼＿＿＿＿＿＿＿
.PP
                    3 ＼＿＿＿＿＿＿＿
.PP
                    4 ／＿＿＿＿＿＿＿
.PP
                    5 ／＿＿＿＿＿＿＿
.PP
                    6 ／＿＿＿＿＿＿＿
.PP
                    7 ／＿＿＿＿＿＿＿
.PP
                    8 ＼＼＼＼＼＼＼＼
.PP
                    9 ＼＿＿＿＿＿＿＿
.PP
                   10 ＼／＼／＼／＼／
.PP
                   11 ＼￣￣￣￣￣￣￣
.PP
                   12 ／／／／／／／／
.PP
                   13 ／￣￣￣￣￣￣￣
.PP
                   14 ／＼／＼／＼／＼
.PP
                   15 ／＿＿＿＿＿＿＿
.PP
    M<周期>        エンベローブ周期。1～65535。
.PP
                   波形に記載している ＿・￣・／・＼ １文字分の長さ
.PP
                   (143x設定値)μ秒。
.PP
    X<文字型変数>; <文字型変数>に記載されたMML命令に置き換える。
.PP
    =<数値型変数>; <数値型変数>に記載された文字列に置き換える。