.TH "PRINT" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
PRINT \- 数字や文字列を出力します。

.SH SYNOPSIS
.B PRINT [#<ファイル番号>,] [<式> ...]

.SH DESCRIPTION
.PP
数字や文字列を出力します。

.SH EXAMPLES
.PP
PRINT A$,B,"MSX";"?"

.SH NOTES
.PP
.PP
テキストモード（SCREEN 0・1）で有効ですが、
.PP
#<ファイル番号> を含む場合はグラフィックモードでも使用できます。
.PP
#<ファイル番号> で指定されたファイルへ出力を行ないます。
.PP
この場合の <ファイル番号> は
.PP
OPEN によって OUTPUT または APPEND で開いておく必要があります。
.PP
#<ファイル番号> がない場合は
.PP
テキストモードでの画面出力となります。
.PP
複数の <式> を連結する文字として ; と , が使用できます。
.PP
; は間がありません。, は14桁区切りで表示されます。
.PP
PRINT の最後に ; がある場合は改行が行なわれません。
.PP
ない場合は改行を行ないます。
.PP
また PRINT のみの場合は改行が行なわれます。
.PP
<式> が数値の場合、左１文字分が符号表示となります。
.PP
正の場合はスペース、負の場合は - となります。
.PP
また、後にも１文字分の空白が付加されます。
.PP
数値が単精度実数型・倍精度実数型の場合、
.PP
それぞれ 6 桁・14 桁までは実数で表記されますが、
.PP
それ以上の桁数を持つ場合は指数表記となります。
.PP
PRINT の代わりに ? を用いる事もできます。