.TH "PUT SPRITE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
PUT SPRITE \- スプライトを表示します

.SH SYNOPSIS
.B PUT SPRITE <スプライト面番号>,
[STEP](<横座標>,<縦座標>),[<色>],[<パターン番号>]

.SH DESCRIPTION
.PP
スプライトを表示します

.SH EXAMPLES
.PP
PUT SPRITE 0,(100,100),10,0

.SH NOTES
.PP
.PP
<スプライト面番号> は 0～31 です。
.PP
1面に一つのスプライトを表示できます。
.PP
複数のスプライトを一面に置いた場合は
.PP
最後のスプライトが表示され、他のスプライトは消えます。
.PP
<横座標> は -32～255、<縦座標> は -32～21
.PP
1（SCREEN 3より前では -32～191）です。
.PP
SCREEN 6・7 でも
.PP
スプライトの横座標は -32～255 となります。
.PP
縦座標はテキスト・グラフィック画面と１ドット下にずれていて、
.PP
グラフィック画面での縦座標 0 が
.PP
スプライトでは -1=255 になっている事にご注意下さい。
.PP
STEP により、PSET・PRESET・DRAW 等で指定された座標からの
.PP
相対指定が行なえます。
.PP
SCREEN 6・7 の場合は最終座標から <横座標> を加え、
.PP
256 で割った余りが表示される横座標となります。
.PP
<色> を指定するとでその色でスプライトを表示できます。
.PP
省略した場合は COLOR の前景色となりますが、
.PP
SCREEN 4 以降では
.PP
COLOR SPRITE・COLOR SPRITE$ で
.PP
定義された色が有効となります。
.PP
<パターン番号> を省略した場合は
.PP
現在スプライト面に表示されているスプライトが用いられます。