.TH "RETURN" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
RETURN \- 実行された GOSUB の次の文へ制御を移します。


.SH SYNOPSIS
.B RETURN [<行番号>]

.SH DESCRIPTION
.PP
実行された GOSUB の次の文へ制御を移します。


.SH EXAMPLES
.PP
RETURN

.SH NOTES
.PP
.PP
GOSUB で実行されたサブルーチンを終了し、
.PP
実行された GOSUB の次の文へ戻ります。
.PP
<行番号> がある場合はその行番号へ強制的に移ります。