.TH "RIGHT$" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
RIGHT$ \- 文字列の右側から指定された数の文字列を取り出します。

.SH SYNOPSIS
.B RIGHT$(<文字列>,<数式>)

.SH DESCRIPTION
.PP
文字列の右側から指定された数の文字列を取り出します。

.SH EXAMPLES
.PP
PRINT RIGHT$("MSX ver 1.0?",4)
 [表示] 1.0?

.SH NOTES
.PP
.PP
指定した数が文字列の総数より大きい場合は
.PP
文字列がそのまま取り出されます。