.TH "RND" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
RND \- <数式>によって指定された 0 以上 1 未満の乱数を発生します。

.SH SYNOPSIS
.B RND(<数式>)

.SH DESCRIPTION
.PP
<数式>によって指定された 0 以上 1 未満の乱数を発生します。

.SH EXAMPLES
.PP
PRINT RND(1)
 [表示] .521896548554265

.SH NOTES
.PP
.PP
<数式> が正の場合は同じ乱数の並びの新しい乱数を返します。
.PP
0 の場合は同じ乱数の並びの前回使った値を返します。
.PP
負の場合はその値に対応した固有の乱数の並びを作ります。
.PP
乱数の並びは、プログラムが実行される度に同じものが使われすが、
.PP
RND(-TIME) を用いる事で毎回異なる乱数の並びを使う事ができます。