.TH "RUN(2)" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
RUN(2) \- フロッピーディスクからファイルを読み込み、そのプログラムを実行します。

.SH SYNOPSIS
.B RUN <ファイルスペック>[,R]

.SH DESCRIPTION
.PP
フロッピーディスクからファイルを読み込み、そのプログラムを実行します。

.SH EXAMPLES
.PP
RUN "GAME.BAS"

.SH NOTES
.PP
.PP
<ファイルスペック> を指定した場合は
.PP
フロッピーディスクからプログラムを読み込んだ後に
.PP
そのプログラムの実行を開始します。
.PP
初期値では開いているファイルが閉じられ、
.PP
メモリ内容はクリアされますが、
.PP
,R を指定するとファイルは開いたままで読み込まれます。