.TH "SCREEN" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SCREEN \- スクリーンモードやスプライトサイズ等の設定を行ないます。

.SH SYNOPSIS
.B SCREEN [<スクリーンモード>][,<スプライトサイズ>]
[,<キークリック>][,<カセットボーレート>]
[,<プリンタ種別>][,<インターレースモード>]

.SH DESCRIPTION
.PP
スクリーンモードやスプライトサイズ等の設定を行ないます。

.SH EXAMPLES
.PP
WIDTH 7,2,,,,,0

.SH NOTES
.PP
.PP
<スクリーンモード> の値は以下の通りです。初期値は 1 です。
.PP
     0 最大80x24文字 テキストモード（ MSX(1) では最大40x24ドット ）
.PP
       前景色・背景色で16色中の各1色
.PP
       文字を横幅6ドットにして表示
.PP
     1 最大32x24文字 テキストモード
.PP
       前景色・背景色・周辺色で16色中の各1色
.PP
     2 256x192ドット グラフィックモード
.PP
       横8ドット毎に16色中の2色
.PP
       MSX2 以降で16色はパレット使用可
.PP
     3 64x48ブロック グラフィックモード
.PP
       1ブロック(4x4ドット)毎に16色中の2色
.PP
       MSX2 以降で16色はパレット使用可
.PP
     4 256x192ドット グラフィックモード（MSX2 以降）
.PP
       横8ドット毎に16色中の2色
.PP
       SCREEN 2 とはスプライトモードが異なる 16色はパレット使用可
.PP
     5 256x212ドット グラフィックモード（MSX2 以降）
.PP
       1ドット毎に16色中の1色
.PP
       16色はパレット使用可
.PP
     6 512x212ドット グラフィックモード（MSX2 以降）
.PP
       1ドット毎に4色中の1色
.PP
       4色はパレット使用可
.PP
     7 512x212ドット グラフィックモード（MSX2 以降・VRAM128KB 以上）
.PP
       1ドット毎に16色中の1色
.PP
       16色はパレット使用可
.PP
     8 256x212ドット グラフィックモード（MSX2 以降・VRAM128KB 以上）
.PP
       1ドット毎に256色中の1色
.PP
       256色は固定
.PP
     9 韓国の MSX2 でハングル文字表示に使用
.PP
       韓国以外の MSX では使用不可
.PP
    10 256x212ドット グラフィックモード（MSX2+ 以降）
.PP
       YJK・RGB 12499色 グラフィック処理あり
.PP
    11 256x212ドット グラフィックモード（MSX2+ 以降）
.PP
       YJK・RGB 12499色 グラフィック処理なし
.PP
    12 256x212ドット グラフィックモード（MSX2+ 以降）
.PP
       YJK 19268色
.PP
<スプライトサイズ> の値は以下の通りです。初期値は 0 です。
.PP
    0 8x8 ドット
.PP
    1 8x8 ドット・縦横 2 倍
.PP
    2 16x16 ドット
.PP
    3 16x16 ドット・縦横 2 倍
.PP
<キークリック> はキークリックした際に
.PP
音を出すか出さないかを設定します。
.PP
値は以下の通りです。初期値は 1 です。
.PP
    0 キークリック音を出さない
.PP
    1 キークリック音を出す
.PP
<カセットボーレート> は
.PP
CSAVE でボーレートを省略した際に用いられる値です。
.PP
値は以下の通りです。初期値は 1 です。
.PP
MSX turbo R では使用できません。
.PP
    1 1200 ボー
.PP
    2 2400 ボー
.PP
<フリンタ種別> の値は以下の通りです。初期値は 0 です。
.PP
    0      MSX 仕様のプリンタ
.PP
    1～255 MSX 以外のプリンタ。
.PP
           グラフィック文字は空白に、
.PP
           半角ひらがなはカタカナに変換して出力します。
.PP
<インターレースモード> の値は以下の通りです。
.PP
初期値は 0 です。MSX2 以降で有効です。
.PP
    0 ノンインターレース（表示ページ）
.nf
    1 インターレース（表示ページ＋表示ページ）
.fi
.PP
    2 ノンインターレース（表示ページ・表示-1ページ交互）
.nf
    3 インターレース（表示ページ＋表示-1ページ交互）
.fi