.TH "SET ADJUST" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SET ADJUST \- 画面の表示位置を調整します。

.SH SYNOPSIS
.B SET ADJUST(<X座標>,<Y座標>)

.SH DESCRIPTION
.PP
画面の表示位置を調整します。

.SH EXAMPLES
.PP
SET BEEP -1,1

.SH NOTES
.PP
.PP
MSX 本体をテレビを用いて表示した際に
.PP
スクリーンモードによっては切れてしまう場合があります。
.PP
それを補正する機能です。
.PP
<X座標> <Y座標> はそれぞれ -8～7 の値です。
.PP
この設定は MSX 本体で SRAM に記録されます。