.TH "SET VIDEO" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SET VIDEO \- スーパーインポーズのモードを設定します。

.SH SYNOPSIS
.B SET VIDEO <モード>[,<モニタ画面密度>[,<VDP カラーバス>]]

.SH DESCRIPTION
.PP
スーパーインポーズのモードを設定します。

.SH EXAMPLES
.PP
SET VIDEO 2

.SH NOTES
.PP
.PP
<モード> は以下の通りです。
.PP
    0 内部同期・コンピュータ画面
.PP
    1 外部同期・コンピュータ画面
.PP
    2 外部同期・スーパーインポーズ
.PP
    3 外部同期・外部ビデオ画面
.PP
<モニタ画面密度> は以下の通りです。
.PP
    0 ノーマル
.PP
    1 ハーフトーン
.PP
<VDP カラーバス> は以下の通りです。
.PP
    0 出力モード
.PP
    1 入力モード