.TH "SET PASSWORD" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SET PASSWORD \- パスワードを設定します。

.SH SYNOPSIS
.B SET PASSWORD <パスワード>

.SH DESCRIPTION
.PP
パスワードを設定します。

.SH EXAMPLES
.PP
SET PROMPT "PaSsWoRd"

.SH NOTES
.PP
.PP
<パスワード>の値は 255 文字以内です。
.PP
起動時にパスワードを聞かれ、入力しないと起動しなくなります。
.PP
ただし [GRAPH]+[STOP] を押しながら起動する事で
.PP
パスワードを聞かれずに起動する事が可能です。
.PP
この設定は MSX 本体では SRAM に記録されます。
.PP
SET PROMPT・SET TITLE と共有しているため、
.PP
これらと含めて最後に設定されたものが有効となります。
.PP
初期状態は SET TITLE "" として下さい。