.TH "SET SCREEN" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SET SCREEN \- WIDTH・SCREEN の状態を保存します。

.SH SYNOPSIS
.B SET SCREEN

.SH DESCRIPTION
.PP
WIDTH・SCREEN の状態を保存します。

.SH EXAMPLES
.PP
SET SCREEN

.SH NOTES
.PP
.PP
この設定は MSX 本体で SRAM に記録されます。
.PP
MSX 起動時に SET SCREEN が実行された状態の
.PP
WIDTH・SCREEN で起動されます。