.TH "SET DATE" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SET DATE \- 日付を設定します。

.SH SYNOPSIS
.B SET DATE <日付>[,A]

.SH DESCRIPTION
.PP
日付を設定します。

.SH EXAMPLES
.PP
SET TIME "03-06-27"

.SH NOTES
.PP
.PP
<日付> は <年>-<月>-<日> で、
.PP
<年> <月> <日> はそれぞれ2桁で指定します。
.PP
また、<年> は西暦の下2桁となります。
.PP
2003年2月1日であれば 03/02/01 となります。
.PP
,A をつけた場合はアラーム時間の日付設定を行ないます。
.PP
MSXPLAYer では使用している Windows の日付がそのまま使われます。