.TH "SET SCROLL" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SET SCROLL \- ハードウェアスクロールを行ないます。

.SH SYNOPSIS
.B SET SCROLL [<横ドット>][,<縦ドット>]
[,<マスクモード>][,<ページモード>]

.SH DESCRIPTION
.PP
ハードウェアスクロールを行ないます。

.SH EXAMPLES
.PP
SET PAGE 50,100,1,1

.SH NOTES
.PP
.PP
<横ドット> は画面左へスクロール量を0～511で指定します。
.PP
<縦ドット> は画面上へスクロール量を0～255で指定します。
.PP
それぞれ初期値は 0 ですが、省略時は最後に指定された値を保持します。
.PP
<マスクモード> は左8ドットを非表示にします。
.PP
マスクしたところを線画する事で線画処理を見せなくする効果があります。
.PP
<ページモード> の値は以下の通りです。
.PP
    0 1 ページによるスクロール
.PP
    1 連続する 2 ページを横に連結してのスクロール
.PP
      （ページは 0 と 1、2 と 3）