.TH "SOUND" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SOUND \- 音源チップにデータを送る

.SH SYNOPSIS
.B SOUND <レジスタ番号>,<データ>

.SH DESCRIPTION
.PP
音源チップにデータを送る

.SH NOTES
.PP
.PP
<レジスタ番号> と <データ> は以下の通りです。
.PP
     0 チャンネル 1 の周波数 (下位 8 ビット) 0～255
.PP
     1 チャンネル 1 の周波数 (上位 4 ビット) 0～15
.PP
     2 チャンネル 2 の周波数 (下位 8 ビット) 0～255
.PP
     3 チャンネル 2 の周波数 (上位 4 ビット) 0～15
.PP
     4 チャンネル 3 の周波数 (下位 8 ビット) 0～255
.PP
     5 チャンネル 3 の周波数 (上位 4 ビット) 0～15
.PP
     6 ノイズ平均周波数 0～31
.PP
     7 チャンネル設定 128～191
.PP
     8 チャンネル 1 の音量 0～16
.PP
     9 チャンネル 2 の音量 0～16
.PP
    10 チャンネル 3 の音量 0～16
.PP
    11 エンベローブ形状 0～15
.PP
    12 エンベローブ周期 (下位8ビット) 0～255
.PP
    13 エンベローブ周期 (上位8ビット) 0～255
.PP
レジスタ 0～5 で指定する周波数は
.PP
二つのレジスタを合わせて 0～4096 となります。
.PP
111860.78125/周波数[Hz] です。
.PP
音程は次の表となります。(16 進数表記)
.PP
例えば O4C の音をチャンネル 1 で出す場合は
.PP
SOUND 0,&HAC:SOUND 1,&H1 となります。
.PP
     ＼   O1  O2  O3  O4  O5  O6  O7  O8
.PP
      C   D5D 6AF 357 1AC 0D6 06B 035 01B
.PP
    C+/D- C9C 64E 327 194 0CA 065 032 019
.PP
      D   BE7 5F4 2FA 17D 0BE 05F 030 018
.PP
    D+/E- B3C 59E 2CF 168 084 05A 02D 016
.PP
      E   A9B 54E 2A7 153 0AA 055 02A 015
.PP
      F   A02 501 281 140 0A0 050 028 014
.PP
    F+/G- 973 4BA 25D 12E 097 04C 026 013
.PP
      G   8EB 476 23B 11D 08F 047 024 012
.PP
    G+/A- 86B 436 21B 10D 087 043 022 011
.PP
      A   7F2 3F9 1FD 0FE 07F 040 020 010
.PP
    A+/B- 780 3C0 1E0 0F0 078 03C 01E 00F
.PP
      B   714 38A 1C5 0E3 071 039 01C 00E
.PP
レジスタ 6 で指定するノイズ平均周波数は
.PP
三つのチャンネルに共通となります。
.PP
111860.78125/周波数[Hz] です。
.PP
レジスタ 7 で指定するチャンネル設定は以下の通りです。
.PP
    bit7 1 固定
.PP
    bit6 0 固定
.PP
    bit5 チャンネル3のノイズ 0=出力 1=非出力
.PP
    bit4 チャンネル2のノイズ 0=出力 1=非出力
.PP
    bit3 チャンネル1のノイズ 0=出力 1=非出力
.PP
    bit2 チャンネル3の音　　 0=出力 1=非出力
.PP
    bit1 チャンネル2の音　　 0=出力 1=非出力
.PP
    bit0 チャンネル1の音　　 0=出力 1=非出力
.PP
レジスタ 8～10 で指定する音量は 0～16 です。
.PP
0～15 は一定値で 0 が最小、15 が最大です。
.PP
16 の場合はレジスタ 11～13 で指定している
.PP
エンベローブが有効となります。
.PP
レジスタ 11・12 のエンベローブ周期は
.PP
SOUND 11 に下位　8 ビット、SOUND 12 に上位 8 ビットを入れます。
.PP
二つのレジスタを合わせて 0～65535 になります。
.PP
波形に記載している ＿・￣・／・＼ １文字分の長さで
.PP
 (143x設定値)μ秒 となります。
.PP
レジスタ 13 のエンベローブ形状は
.PP
音の変化の波形を指定します。以下の通りです。
.PP
    ￣ = V15　＿ = V0　／ = V0→V15　＼ V0→V15
.PP
     0 ＼＿＿＿＿＿＿＿
.PP
     1 ＼＿＿＿＿＿＿＿
.PP
     2 ＼＿＿＿＿＿＿＿
.PP
     3 ＼＿＿＿＿＿＿＿
.PP
     4 ／＿＿＿＿＿＿＿
.PP
     5 ／＿＿＿＿＿＿＿
.PP
     6 ／＿＿＿＿＿＿＿
.PP
     7 ／＿＿＿＿＿＿＿
.PP
     8 ＼＼＼＼＼＼＼＼
.PP
     9 ＼＿＿＿＿＿＿＿
.PP
    10 ＼／＼／＼／＼／
.PP
    11 ＼￣￣￣￣￣￣￣
.PP
    12 ／／／／／／／／
.PP
    13 ／￣￣￣￣￣￣￣
.PP
    14 ／＼／＼／＼／＼
.PP
    15 ／＿＿＿＿＿＿＿