.TH "SPC" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SPC \- 指定した数の空白を表示します。

.SH SYNOPSIS
.B SPC(<数式>)

.SH DESCRIPTION
.PP
指定した数の空白を表示します。

.SH EXAMPLES
.PP
PRINT "SPC";SPC(10);"SPC"
 [表示] SPC          SPC

.SH NOTES
.PP
.PP
TAB は左端から空白を表示しますが、
.PP
SPC は指定位置から空白を表示します。
.PP
<数式> の値は 0～255 です。