.TH "STRIG OFF" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
STRIG OFF \- ON STRIG GOSUB による割り込みを停止します。

.SH SYNOPSIS
.B STRIG(<番号>) OFF

.SH DESCRIPTION
.PP
ON STRIG GOSUB による割り込みを停止します。

.SH EXAMPLES
.PP
STRIG(1) OFF

.SH NOTES
.PP
.PP
<番号> は以下とおりです。
.PP
    0 スペースキー
.PP
    1 ポート 1 の A ボタン
.PP
    2 ポート 2 の A ボタン
.PP
    3 ポート 1 の B ボタン
.PP
    4 ポート 2 の B ボタン