.TH "SWAP" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
SWAP \- ２つの変数値を交換します。

.SH SYNOPSIS
.B SWAP(<変数名 1>,<変数名 2>)

.SH DESCRIPTION
.PP
２つの変数値を交換します。

.SH EXAMPLES
.PP
A=1:B=2:SWAP A,B:PRINT A,B
 [表示] 2       1

.SH NOTES
.PP
.PP
<変数名 1> と <変数名 2> の値を交換します。
.PP
<変数名 1> と <変数名 2> 型は一致していなければいけません。