.TH "USR" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
USR \- 機械語で作られたプログラムを実行します。

.SH SYNOPSIS
.B USR[<番号>](<引数>)

.SH DESCRIPTION
.PP
機械語で作られたプログラムを実行します。

.SH EXAMPLES
.PP
U=USR(0)
M$=USR1("MSX")

.SH NOTES
.PP
.PP
DEF USR で指令された開始アドレスから実行を開始します。
.PP
<番号> は 0～9 です。省略時は 0 になります。
.PP
<引数> は BASIC から機械語へ渡される内容として指定します。
.PP
呼び出されたマシン語からは
.PP
レジスタ A または &HF663 の値で型を得ます。
.PP
値と <引数> の取り出しは次のとおりです。
.PP
    2 整数型
.PP
      &HF7F8～&HF7F9 の 2 バイトに <引数> が入ります。
.PP
    3 文字型
.PP
      DE レジスタに参照先の番地があります。
.PP
      参照先の番地には文字列の長さ、
.PP
      続く 2 バイトが文字列が入っている番地が入ります。
.PP
      3 バイトはストリングディスクリプタとなっています。
.PP
    4 単精度実数型
.PP
      &HF7F6～&HF7F9 の 4 バイトに <引数> が入ります。
.PP
      &HF7F6 が指数、&HF7F7～&HF7F9 が仮数となります。
.PP
    8 倍精度整数型
.PP
      &HF7F6～&HF7FD の 8 バイトに <引数> が入ります。
.PP
      &Hf7F6 が指数、&HF7F7～&HF7FD が仮数となります。
.PP
HL は文字型を除き &HF7F6 のポインターです。
.PP
従って 整数型は HL に入っている参照先番地 + 2 になっています。
.PP
文字列型に限り DE を参照する事にご注意下さい。
.PP
資料によっては A・HL・DE のレジスタのみで記載がありますが、
.PP
実際にそのレジスタの値は文字列を除き固定となっています。
.PP
返される値は機械語から BASIC へ渡される内容です。
.PP
マシン語から BASIC への引き継ぎは <引数> と同じ形にします。