.TH "VDP" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
VDP \- VDP へデータを書き込んだり、レジスタからデータを読み出したりします。

.SH SYNOPSIS
.B VDP(<レジスタ番号>)

.SH DESCRIPTION
.PP
VDP へデータを書き込んだり、レジスタからデータを読み出したりします。

.SH EXAMPLES
.PP
VDP(1)=&HE1
 [意味] VDP(ビデオディスプレイプロセッサ)のレジスタ1に
        &HE1 というデータを書き込みます。

.SH NOTES
.PP
.PP
読み書きできる値は次の通りです。
.PP
    レジスタ 0～7 (読・書)       0～7   MSX 全機種
.PP
    ステータスレジスタ 0 (読)    8      MSX 全機種
.PP
    レジスタ 8 以降(読・書)      9～24  MSX2 以降
.PP
                                 26～28 MSX2+ 以降
.PP
    ステータスレジスタ 1～9 (読) -1～-9 MSX2 以降