.TH "VPEEK" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
VPEEK \- VRAM 上の指定した番地の内容を読み出します。

.SH SYNOPSIS
.B VPEEK(<番地>)

.SH DESCRIPTION
.PP
VRAM 上の指定した番地の内容を読み出します。

.SH EXAMPLES
.PP
PRINT VPEEK(0)

.SH NOTES
.PP
.PP
番地の値は 0～&HFFFF(65535)
.PP
返されるデータは 0～255 です。
.PP
MSX2 以降の場合は
.PP
SET PAGE 命令で指定したページからのオフセットとなります。