.TH "WAIT" "1" "2025-05-29" "MSX-BASIC" "User Commands"
.SH NAME
WAIT \- 入力ポートに指定した値が入るまでプログラムの実行を中断します。

.SH SYNOPSIS
.B WAIT<ポート番号>,<式1>[<,式2>]

.SH DESCRIPTION
.PP
入力ポートに指定した値が入るまでプログラムの実行を中断します。

.SH EXAMPLES
.PP
WAIT 1,&H22,&H22

.SH NOTES
.PP
.PP
<ポート番号> で指定した入力ポートから
.PP
読み込んだデータと<式2>との XOR の結果を
.PP
<式1> で AND した結果が真になるまで
.PP
プログラムの実行を中断します。
.PP
<式2> を省略した場合は 0 が使われます。
.PP
WAIT はハードウェアに密着した命令で
.PP
それぞれの MSX で異なる動作をする場合があります。
.PP
広く公表されるプログラムでは使用しないよう
.PP
記載がある解説書もあります。